export {default as ProfileForm} from './UserProfileForm/ProfileForm';
export {default as Dashboard} from './Dashboard/Dashboard';
export {default as HallForm} from './HallForm/HallForm';
export {default as OrderHistory} from './OrderHistoryPage/OrderHistoryPage';
export {default as OrderDetailsPage} from './OrderDetailsPage/OrderDetailsPage';
export {default as SettingsComponent} from './UserSettings/UserSettings'; 
export {default as UserProfileUpdate} from './UserProfileUpdate/UserProfileUpdate';
export {default as Notification} from './Notifications/Notifications'; 
export {default as MyCart} from './MyCart/MyCart';
export {default as Favorites} from './Favorites/Favorites';
export {default as BookingConfirmation} from './BookingConfirmationPage/BookingConfirmation'